### PR TITLE
French Translation from SicFR57

### PR DESCRIPTION
**Pull request by SicFR57**
moddesc.xml file for french translation:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<modDesc descVersion="21">
    <author>Freelance Modding Crew</author>
    <version>2.3.7</version>
    <contributors>SchorschiBW, ja_pizgam, Gonimy_Vetrom, JakobT, pokers</contributors>

```
<title>
    <en>Glance</en>
    <de>Glance</de>
    <pl>Glance</pl>
    <ru>Glance</ru>
    <hu>Glance</hu>
    <it>Glance</it>
    <fr>Glance</fr>
</title>

<description>
    <en>
```

<![CDATA[A notification-and-status utility that can be configured to show only what
you need to see

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </en>

```
    <de> 
```

<![CDATA[Ein Mitteilungs- und Status-Tool das so konfiguriert werden kann dass man 
nur das sieht was man braucht.

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </de>

```
    <pl> 
```

<![CDATA[Użyteczne narzędzie powiadamiania i statusu, które może być skonfigurowane
tak, aby pokazywać to, co chcesz zobaczyć. 

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </pl>         

```
    <ru> 
```

<![CDATA[Утилита для отображения уведомлений/статуса техники и животных. Может работать в соответствии
с настройками, чтобы показывать только то, что Вы хотите видеть. 

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </ru>

```
    <hu>
```

<![CDATA[Egy állapot- és tevékenység kijelző mód, amiben te magad választhatod meg
mit szeretnél látni.

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </hu>
        <it>
<![CDATA[Un servizio di notifica e stato che può essere configurato per mostrare
solo quello che hai bisogno di vedere 

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </it>
        <fr>
<![CDATA[Un utilitaire de notification et statut qui peut être configuré pour afficher ce que vous voulez.

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
        </fr>
    </description>

```
<iconFilename>store_Glance.dds</iconFilename>
<multiplayer supported="true"/>

<l10n filenamePrefix="modDesc_l10n" /> <!-- Load the corresponding modDesc_l10n_<language>.XML file, or revert to 'en'/'de'. -->

<extraSourceFiles>
    <sourceFile filename="Glance.lua" />
</extraSourceFiles>

<inputBindings>
    <input name="GlanceMore"    category="ONFOOT VEHICLE" key1="KEY_lalt KEY_m" key2="" button="" device="" mouse="" />
    <input name="GlanceLess"    category="ONFOOT VEHICLE" key1="KEY_lalt KEY_l" key2="" button="" device="" mouse="" />
</inputBindings>
```

</modDesc>

modDesc_l10n_fr.xml:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<l10n>
    
    <description>
<![CDATA[Un utilitaire de notification et statut qui peut être configuré pour afficher ce que vous voulez.

Decker_MMIV - fs-uk.com, forum.farming-simulator.com, modhoster.com]]>
    </description>

```
<texts>
    <text name="hired"              text="(Ouvrier)"      />
    <text name="dismissed"          text="(Terminé!)"  />
    <text name="courseplay"         text="(courseplay)" />
    <text name="followme"           text="(followme)"   />
    <text name="broken"             text="(En panne!)"    />

    <text name="north"              text="N"    />
    <text name="northeast"          text="NE"   />
    <text name="east"               text="E"    />
    <text name="southeast"          text="SE"   />
    <text name="south"              text="S"    />
    <text name="southwest"          text="SO"   />
    <text name="west"               text="O"    />
    <text name="northwest"          text="NO"   />
    <text name="center"             text="C"    />

    <text name="closestfield"       text="F%d"  />

    <text name="fieldsWithBales"    text="Champs avec bottes:"   />
    <text name="fieldNumAndBales"   text=" F%d(x%d)"            />
    <text name="balesElsewhere"     text="Bottes ailleurs(x%d)" />

    <text name="fuellow"            text="Jauge basse (%s%%)"  />
    <text name="engineon"           text="Moteur allumé!"    />
    <text name="collision"          text="Bloqué"          />

    <text name="speed+Unit"         text="%.1f %s"  />
    <text name="speedSlow"          text="Haut régime" />
    <text name="speedIdle"          text="Au neutre"     />
    <text name="cp_waiting"         text="En Attente"  />

    <text name="unknownFillType"    text="(inconnu)"    />
    <text name="bales"              text="Bottes"        />

    <text name="task_Harvesting"    text="Récolte"       />
    <text name="task_Defoliator"    text="Enlève les fanes"      />
    <text name="task_Loading_bales" text="Charge des bottes"    />
    <text name="task_Wrapping_bale" text="Enrubanne"    />
    <text name="task_Baling"        text="Presse"           />
    <text name="task_Foraging"      text="Autocharge"         />
    <text name="task_Tedding"       text="Fane"          />
    <text name="task_Swathing"      text="Andaine"         />
    <text name="task_Mowing"        text="Fauche"           />
    <text name="task_Spraying"      text="Pulvérise"         />
    <text name="task_Seeding"       text="Sème"          />
    <text name="task_Bedding"       text="Paille"          />
    <text name="task_Feeding"       text="Nourri"          />
    <text name="task_Cutting"       text="Moissonne"          />
    <text name="task_Cultivating"   text="Cultive"      />
    <text name="task_Ploughing"     text="Laboure"        />
    <text name="task_Unloading"     text="Décharge"        />
    <text name="task_Transporting"  text="Transporte"     />
    <text name="task_StumpCutting"  text="Coupe les souches"    />
    <text name="task_WoodCrushing"  text="Broie du bois"    />
    <text name="task_TreePlanting"  text="Plante des arbres"    />

    <text name="config_error"       text="'Glance' a un problème avec le chargement du fichier Glance_Config.XML.
    Veuillez vérifier la console dans le jeu ou le fichier LOG.TXT pour de plus de détails.
```

Ou supprimez le fichier Glance_Config.XML." />

```
    <text name="GlanceMore"         text="Glance:Plus de détails"   />
    <text name="GlanceLess"         text="Glance:Moins de détails"   />

    <text name="GlanceMinLevel"     text="Niveau minimum de notification est à: %d" />
</texts>
```

</l10n>

### CODE REVIEW

**Comment by DeckerMMIV** [comment]
Hmm?
I can not use your 'pull request' as it is. Your fork of my repository is at a wrong and older branch 'FS2015'. - _And yes, using a distributed version control system like GIT is very confusing, even for me and I'm a programmer by profession._

Also the comment you supplied, with the content of `ModDesc_l10n_fr.xml`, is too garbled so I can not just copy-and-paste it. - Please use https://gist.github.com for attaching those files, if the pull request can not be fixed.

**Comment by SicFR57** [comment]
Ok Docker. I'll correct that.

**Comment by SicFR57** [comment]
Hey,

try here:
https://gist.github.com/SicFR57/57101bff5d705c8899c0

2015-03-27 19:58 GMT+01:00 Grégory CLEMENT gregory.clement.1@gmail.com:

> Ok Docker. I'll correct that.
> Le 27 mars 2015 19:41, "DeckerMMIV" notifications@github.com a écrit :
> 
> Hmm?
> 
> > I can not use your 'pull request' as it is. Your fork of my repository is
> > at a wrong and older branch 'FS2015'. - _And yes, using a distributed
> > version control system like GIT is very confusing, even for me and I'm a
> > programmer by profession._
> > 
> > Also the comment you supplied, with the content of ModDesc_l10n_fr.xml,
> > is too garbled so I can not just copy-and-paste it. - Please use
> > https://gist.github.com for attaching those files, if the pull request
> > can not be fixed.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/DeckerMMIV/FarmSim_Mod_Glance/pull/4#issuecomment-87048737
> > .

## 

Cordialement,

Grégory CLEMENT

**Comment by DeckerMMIV** [comment]
Thank you. - The file is now in the repository, so this 'pull request' can be closed/deleted.

**Pull request closed without merging**
